### ISSUE TITLE
Bundling with semantic-ui-css breaks bundler

### ISSUE THREAD

**Issue by JamesSingleton** [americanexpress/one-app-cli#79]
# 🐞 Bug Report

## Describe the bug

While following the `Get Started` docs for [semantic-ui-react](https://react.semantic-ui.com/usage/), I ran into an issue with importing their css from their `semantic-ui-css` library.

## To Reproduce

1. Create a module (in my case I created a root module)
```bash
npx -p yo -p @americanexpress/generator-one-app-module -- yo @americanexpress/one-app-module
```
2. `npm i -S semantic-ui-react semantic-ui-css`
3. Inside your root module's `.jsx` file import the css `import 'semantic-ui-css/semantic.min.css'`
4. Run `npm run build` or `npm run watch:build`
5. See error in terminal

## Expected behavior

As a developer using One App, I should be able to use `semantic-ui-react` along with their css library.

## Actual Behavior

<details><summary>Show Error Stack</summary

<p>

```bash

./node_modules/semantic-ui-css/themes/default/assets/fonts/icons.woff
Module build failed (from ./node_modules/url-loader/dist/cjs.js):
Error: Cannot find module 'file-loader'
Require stack:
- D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\index.js
- D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\cjs.js
- D:\Coding\suburbify\suburbify-root\node_modules\loader-runner\lib\loadLoader.js
- D:\Coding\suburbify\suburbify-root\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\NormalModule.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\NormalModuleFactory.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\Compiler.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\webpack.js
- D:\Coding\suburbify\suburbify-root\node_modules\@americanexpress\one-app-bundler\bin\bundle-module.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.loader (D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\index.js:120:20)
 @ ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/@americanexpress/purgecss-loader/loader.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/semantic-ui-css/semantic.min.css) 6:36-87
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.js undefined
./node_modules/semantic-ui-css/themes/default/assets/fonts/outline-icons.woff
Module build failed (from ./node_modules/url-loader/dist/cjs.js):
Error: Cannot find module 'file-loader'
Require stack:
- D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\index.js
- D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\cjs.js
- D:\Coding\suburbify\suburbify-root\node_modules\loader-runner\lib\loadLoader.js
- D:\Coding\suburbify\suburbify-root\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\NormalModule.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\NormalModuleFactory.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\Compiler.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\webpack.js
- D:\Coding\suburbify\suburbify-root\node_modules\@americanexpress\one-app-bundler\bin\bundle-module.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.loader (D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\index.js:120:20)
 @ ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/@americanexpress/purgecss-loader/loader.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/semantic-ui-css/semantic.min.css) 11:36-95
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.js undefined
./node_modules/semantic-ui-css/themes/default/assets/fonts/brand-icons.woff
Module build failed (from ./node_modules/url-loader/dist/cjs.js):
Error: Cannot find module 'file-loader'
Require stack:
- D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\index.js
- D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\cjs.js
- D:\Coding\suburbify\suburbify-root\node_modules\loader-runner\lib\loadLoader.js
- D:\Coding\suburbify\suburbify-root\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\NormalModule.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\NormalModuleFactory.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\Compiler.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\webpack.js
- D:\Coding\suburbify\suburbify-root\node_modules\@americanexpress\one-app-bundler\bin\bundle-module.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.loader (D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\index.js:120:20)
 @ ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/@americanexpress/purgecss-loader/loader.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/semantic-ui-css/semantic.min.css) 16:37-94
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.js undefined
./node_modules/semantic-ui-css/themes/default/assets/fonts/icons.woff2 1:4
Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders    
(Source code omitted for this binary file)
 @ ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/@americanexpress/purgecss-loader/loader.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/semantic-ui-css/semantic.min.css) 5:36-88
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.js undefined
./node_modules/semantic-ui-css/themes/default/assets/fonts/outline-icons.woff2 1:4
Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders    
(Source code omitted for this binary file)
 @ ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/@americanexpress/purgecss-loader/loader.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/semantic-ui-css/semantic.min.css) 10:36-96
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.js undefined
./node_modules/semantic-ui-css/themes/default/assets/fonts/brand-icons.woff2 1:4
Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders    
(Source code omitted for this binary file)
 @ ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/@americanexpress/purgecss-loader/loader.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/semantic-ui-css/semantic.min.css) 15:37-95
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.js undefined
asset size limit: The following asset(s) exceed the recommended size limit (195 KiB).
This can impact web performance.
Assets: 
  suburbify-root.legacy.browser.js (4.43 MiB) undefined
entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (4.43 MiB)
      suburbify-root.legacy.browser.js
 undefined
webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/ undefined
./node_modules/semantic-ui-css/themes/default/assets/fonts/icons.woff
Module build failed (from ./node_modules/url-loader/dist/cjs.js):
Error: Cannot find module 'file-loader'
Require stack:
- D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\index.js
- D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\cjs.js
- D:\Coding\suburbify\suburbify-root\node_modules\loader-runner\lib\loadLoader.js
- D:\Coding\suburbify\suburbify-root\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\NormalModule.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\NormalModuleFactory.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\Compiler.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\webpack.js
- D:\Coding\suburbify\suburbify-root\node_modules\@americanexpress\one-app-bundler\bin\bundle-module.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.loader (D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\index.js:120:20)
 @ ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/@americanexpress/purgecss-loader/loader.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/semantic-ui-css/semantic.min.css) 6:36-87
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.js undefined
./node_modules/semantic-ui-css/themes/default/assets/fonts/outline-icons.woff
Module build failed (from ./node_modules/url-loader/dist/cjs.js):
Error: Cannot find module 'file-loader'
Require stack:
- D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\index.js
- D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\cjs.js
- D:\Coding\suburbify\suburbify-root\node_modules\loader-runner\lib\loadLoader.js
- D:\Coding\suburbify\suburbify-root\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\NormalModule.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\NormalModuleFactory.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\Compiler.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\webpack.js
- D:\Coding\suburbify\suburbify-root\node_modules\@americanexpress\one-app-bundler\bin\bundle-module.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.loader (D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\index.js:120:20)
 @ ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/@americanexpress/purgecss-loader/loader.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/semantic-ui-css/semantic.min.css) 11:36-95
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.js undefined
./node_modules/semantic-ui-css/themes/default/assets/fonts/brand-icons.woff
Module build failed (from ./node_modules/url-loader/dist/cjs.js):
Error: Cannot find module 'file-loader'
Require stack:
- D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\index.js
- D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\cjs.js
- D:\Coding\suburbify\suburbify-root\node_modules\loader-runner\lib\loadLoader.js
- D:\Coding\suburbify\suburbify-root\node_modules\loader-runner\lib\LoaderRunner.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\NormalModule.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\NormalModuleFactory.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\Compiler.js
- D:\Coding\suburbify\suburbify-root\node_modules\webpack\lib\webpack.js
- D:\Coding\suburbify\suburbify-root\node_modules\@americanexpress\one-app-bundler\bin\bundle-module.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.loader (D:\Coding\suburbify\suburbify-root\node_modules\url-loader\dist\index.js:120:20)
 @ ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/@americanexpress/purgecss-loader/loader.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/semantic-ui-css/semantic.min.css) 16:37-94
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.js undefined
./node_modules/semantic-ui-css/themes/default/assets/fonts/outline-icons.woff2 1:4
Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders    
(Source code omitted for this binary file)
 @ ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/@americanexpress/purgecss-loader/loader.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/semantic-ui-css/semantic.min.css) 10:36-96
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.js undefined
./node_modules/semantic-ui-css/themes/default/assets/fonts/icons.woff2 1:4
Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders    
(Source code omitted for this binary file)
 @ ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/@americanexpress/purgecss-loader/loader.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/semantic-ui-css/semantic.min.css) 5:36-88
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.js undefined
./node_modules/semantic-ui-css/themes/default/assets/fonts/brand-icons.woff2 1:4
Module parse failed: Unexpected character '' (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders    
(Source code omitted for this binary file)
 @ ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/@americanexpress/purgecss-loader/loader.js??ref--8-2!./node_modules/sass-loader/dist/cjs.js??ref--8-3!./node_modules/semantic-ui-css/semantic.min.css) 15:37-95
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/index.js undefined
asset size limit: The following asset(s) exceed the recommended size limit (195 KiB).
This can impact web performance.
Assets: 
  suburbify-root.browser.js (4.41 MiB) undefined
entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (4.41 MiB)
      suburbify-root.browser.js
 undefined
webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/ undefined
```
</p>
</details>

### System:
 - OS: Windows 10 10.0.19041
 - CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
 - Memory: 4.65 GB / 15.95 GB
### Binaries:
 - Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD

### npmPackages:
 - @americanexpress/one-app-bundler: ^6.6.0 => 6.6.0
 - @americanexpress/one-app-ducks: ^4.1.0 => 4.1.0
 - @americanexpress/one-app-runner: ^6.6.0 => 6.6.0
 - @commitlint/cli: ^8.3.5 => 8.3.5
 - @commitlint/config-conventional: ^8.3.4 => 8.3.4
 - babel-preset-amex: ^3.4.0 => 3.4.0
 - content-security-policy-builder: ^2.1.0 => 2.1.0
 - eslint: ^7.2.0 => 7.2.0
 - eslint-config-amex: ^12.2.0 => 12.2.0
 - glob: ^7.1.6 => 7.1.6
 - holocron: ^1.0.0 => 1.1.0
 - holocron-module-route: ^1.0.0 => 1.1.0
 - husky: ^4.2.3 => 4.2.5
 - iguazu: ^3.0.2 => 3.0.2
 - iguazu-holocron: ^1.1.0 => 1.1.0
 - immutable: ^4.0.0-rc.12 => 4.0.0-rc.12
 - ip: ^1.1.5 => 1.1.5
 - prop-types: ^15.7.2 => 15.7.2
 - react: ^16.13.0 => 16.13.1
 - react-dom: ^16.13.0 => 16.13.1
 - react-helmet: ^6.0.0 => 6.0.0
 - react-intl: ^4.6.9 => 4.6.9
 - react-redux: ^7.2.0 => 7.2.0
 - redux: ^4.0.5 => 4.0.5
 - rimraf: ^3.0.2 => 3.0.2
 - semantic-ui-css: ^2.4.1 => 2.4.1
 - semantic-ui-react: ^0.88.2 => 0.88.2
### npmGlobalPackages:
 - npm: 6.14.5
 - yarn: 1.22.4

**Comment by JamesSingleton** [comment]
This was fixed in https://github.com/americanexpress/one-app-cli/pull/124. However, you need to disable `purgecss` as libraries like `semantic-ui-react` do not play nicely with `purgecss`
